version: '3'

services:
   front: &client
     build: .
     ports:
     - "3333:5000"
     - "3336:3000"
     volumes:
       - ".:/usr/src"
   front-dev:
     <<: *client
     entrypoint: npm run start
